// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: api/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteResponse_Type int32

const (
	ExecuteResponse_TOKEN         ExecuteResponse_Type = 0 // Incremental text token
	ExecuteResponse_TOOL_CALL     ExecuteResponse_Type = 1 // The LLM wants to run a tool
	ExecuteResponse_TOOL_RESULT   ExecuteResponse_Type = 2 // Results from a tool execution
	ExecuteResponse_ERROR         ExecuteResponse_Type = 3 // Error during processing
	ExecuteResponse_DONE          ExecuteResponse_Type = 4 // Final completion marker
	ExecuteResponse_PLAN_PROPOSAL ExecuteResponse_Type = 5 // A multi-phase plan awaiting confirmation
	ExecuteResponse_STATUS        ExecuteResponse_Type = 6 // System status notice (e.g. Fallback alerts)
)

// Enum value maps for ExecuteResponse_Type.
var (
	ExecuteResponse_Type_name = map[int32]string{
		0: "TOKEN",
		1: "TOOL_CALL",
		2: "TOOL_RESULT",
		3: "ERROR",
		4: "DONE",
		5: "PLAN_PROPOSAL",
		6: "STATUS",
	}
	ExecuteResponse_Type_value = map[string]int32{
		"TOKEN":         0,
		"TOOL_CALL":     1,
		"TOOL_RESULT":   2,
		"ERROR":         3,
		"DONE":          4,
		"PLAN_PROPOSAL": 5,
		"STATUS":        6,
	}
)

func (x ExecuteResponse_Type) Enum() *ExecuteResponse_Type {
	p := new(ExecuteResponse_Type)
	*p = x
	return p
}

func (x ExecuteResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecuteResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_agent_proto_enumTypes[0].Descriptor()
}

func (ExecuteResponse_Type) Type() protoreflect.EnumType {
	return &file_api_v1_agent_proto_enumTypes[0]
}

func (x ExecuteResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecuteResponse_Type.Descriptor instead.
func (ExecuteResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{3, 0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_api_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelId       string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_api_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GetInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Query          string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ExecuteResponse_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=v1.ExecuteResponse_Type" json:"type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                // Text content or JSON for tools
	SkillId       string                 `protobuf:"bytes,3,opt,name=skill_id,json=skillId,proto3" json:"skill_id,omitempty"` // ID if it's a tool-related event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetType() ExecuteResponse_Type {
	if x != nil {
		return x.Type
	}
	return ExecuteResponse_TOKEN
}

func (x *ExecuteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExecuteResponse) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

var File_api_v1_agent_proto protoreflect.FileDescriptor

const file_api_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/agent.proto\x12\x02v1\"\x10\n" +
	"\x0eGetInfoRequest\"^\n" +
	"\x0fGetInfoResponse\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"O\n" +
	"\x0eExecuteRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"\xdb\x01\n" +
	"\x0fExecuteResponse\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.v1.ExecuteResponse.TypeR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bskill_id\x18\x03 \x01(\tR\askillId\"e\n" +
	"\x04Type\x12\t\n" +
	"\x05TOKEN\x10\x00\x12\r\n" +
	"\tTOOL_CALL\x10\x01\x12\x0f\n" +
	"\vTOOL_RESULT\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\b\n" +
	"\x04DONE\x10\x04\x12\x11\n" +
	"\rPLAN_PROPOSAL\x10\x05\x12\n" +
	"\n" +
	"\x06STATUS\x10\x062x\n" +
	"\fAgentService\x124\n" +
	"\aExecute\x12\x12.v1.ExecuteRequest\x1a\x13.v1.ExecuteResponse0\x01\x122\n" +
	"\aGetInfo\x12\x12.v1.GetInfoRequest\x1a\x13.v1.GetInfoResponseB)Z'github.com/patagonicrune/vraxter/api/v1b\x06proto3"

var (
	file_api_v1_agent_proto_rawDescOnce sync.Once
	file_api_v1_agent_proto_rawDescData []byte
)

func file_api_v1_agent_proto_rawDescGZIP() []byte {
	file_api_v1_agent_proto_rawDescOnce.Do(func() {
		file_api_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_agent_proto_rawDesc), len(file_api_v1_agent_proto_rawDesc)))
	})
	return file_api_v1_agent_proto_rawDescData
}

var file_api_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_agent_proto_goTypes = []any{
	(ExecuteResponse_Type)(0), // 0: v1.ExecuteResponse.Type
	(*GetInfoRequest)(nil),    // 1: v1.GetInfoRequest
	(*GetInfoResponse)(nil),   // 2: v1.GetInfoResponse
	(*ExecuteRequest)(nil),    // 3: v1.ExecuteRequest
	(*ExecuteResponse)(nil),   // 4: v1.ExecuteResponse
}
var file_api_v1_agent_proto_depIdxs = []int32{
	0, // 0: v1.ExecuteResponse.type:type_name -> v1.ExecuteResponse.Type
	3, // 1: v1.AgentService.Execute:input_type -> v1.ExecuteRequest
	1, // 2: v1.AgentService.GetInfo:input_type -> v1.GetInfoRequest
	4, // 3: v1.AgentService.Execute:output_type -> v1.ExecuteResponse
	2, // 4: v1.AgentService.GetInfo:output_type -> v1.GetInfoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_agent_proto_init() }
func file_api_v1_agent_proto_init() {
	if File_api_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_agent_proto_rawDesc), len(file_api_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_agent_proto_goTypes,
		DependencyIndexes: file_api_v1_agent_proto_depIdxs,
		EnumInfos:         file_api_v1_agent_proto_enumTypes,
		MessageInfos:      file_api_v1_agent_proto_msgTypes,
	}.Build()
	File_api_v1_agent_proto = out.File
	file_api_v1_agent_proto_goTypes = nil
	file_api_v1_agent_proto_depIdxs = nil
}
