// Copyright (c) 2026 Vraxter. All rights reserved.
// 
// This file is part of Vraxter.
// Vraxter is free software licensed under the GNU Affero General Public License (AGPL) v3.0.
// See the LICENSE file in the project root for full license information.
//
// For commercial licensing inquiries, contact Vraxter.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.2
// source: api/v1/agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Execute_FullMethodName               = "/v1.AgentService/Execute"
	AgentService_GetInfo_FullMethodName               = "/v1.AgentService/GetInfo"
	AgentService_ListHistory_FullMethodName           = "/v1.AgentService/ListHistory"
	AgentService_GetConversation_FullMethodName       = "/v1.AgentService/GetConversation"
	AgentService_GetSupportedProviders_FullMethodName = "/v1.AgentService/GetSupportedProviders"
	AgentService_ConfigureProvider_FullMethodName     = "/v1.AgentService/ConfigureProvider"
	AgentService_ListProviders_FullMethodName         = "/v1.AgentService/ListProviders"
	AgentService_DiscoverModels_FullMethodName        = "/v1.AgentService/DiscoverModels"
	AgentService_RegisterModel_FullMethodName         = "/v1.AgentService/RegisterModel"
	AgentService_ListModels_FullMethodName            = "/v1.AgentService/ListModels"
	AgentService_SubscribeEvents_FullMethodName       = "/v1.AgentService/SubscribeEvents"
	AgentService_GetActiveJobs_FullMethodName         = "/v1.AgentService/GetActiveJobs"
	AgentService_GetConfig_FullMethodName             = "/v1.AgentService/GetConfig"
	AgentService_UpdateConfig_FullMethodName          = "/v1.AgentService/UpdateConfig"
	AgentService_ListSkills_FullMethodName            = "/v1.AgentService/ListSkills"
	AgentService_GetSkillInfo_FullMethodName          = "/v1.AgentService/GetSkillInfo"
	AgentService_InstallSkill_FullMethodName          = "/v1.AgentService/InstallSkill"
	AgentService_DownloadSkill_FullMethodName         = "/v1.AgentService/DownloadSkill"
	AgentService_InjectSkill_FullMethodName           = "/v1.AgentService/InjectSkill"
	AgentService_InspectSkill_FullMethodName          = "/v1.AgentService/InspectSkill"
	AgentService_DeleteSkill_FullMethodName           = "/v1.AgentService/DeleteSkill"
	AgentService_TrustSkill_FullMethodName            = "/v1.AgentService/TrustSkill"
	AgentService_GenerateToken_FullMethodName         = "/v1.AgentService/GenerateToken"
	AgentService_RevokeToken_FullMethodName           = "/v1.AgentService/RevokeToken"
	AgentService_ListTokens_FullMethodName            = "/v1.AgentService/ListTokens"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService manages the interaction between User Clients and The Brain
type AgentServiceClient interface {
	// Execute sends a natural language query and receives a stream of events
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error)
	// GetInfo returns the current status and metadata of the Vraxter Engine
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// ListHistory returns the most recent conversations
	ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error)
	// GetConversation returns all messages for a specific conversation
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error)
	// GetSupportedProviders returns all registered provider types (google, openai, etc.)
	GetSupportedProviders(ctx context.Context, in *GetSupportedProvidersRequest, opts ...grpc.CallOption) (*GetSupportedProvidersResponse, error)
	// ConfigureProvider creates or updates a provider configuration
	ConfigureProvider(ctx context.Context, in *ConfigureProviderRequest, opts ...grpc.CallOption) (*ConfigureProviderResponse, error)
	// ListProviders returns all configured providers
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	// DiscoverModels fetches available models from the provider's API
	DiscoverModels(ctx context.Context, in *DiscoverModelsRequest, opts ...grpc.CallOption) (*DiscoverModelsResponse, error)
	// RegisterModel saves a discovered model to the local database
	RegisterModel(ctx context.Context, in *RegisterModelRequest, opts ...grpc.CallOption) (*RegisterModelResponse, error)
	// ListModels returns all registered models, optionally filtered by provider
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// SubscribeEvents opens a persistent, one-way stream from the engine to the client
	// used to push asynchronous background jobs and swarm notifications.
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemEvent], error)
	// GetActiveJobs returns all currently tracked background daemons
	GetActiveJobs(ctx context.Context, in *GetActiveJobsRequest, opts ...grpc.CallOption) (*GetActiveJobsResponse, error)
	// --- Configuration Management ---
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// --- Skills & Hub Management ---
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error)
	GetSkillInfo(ctx context.Context, in *GetSkillInfoRequest, opts ...grpc.CallOption) (*GetSkillInfoResponse, error)
	InstallSkill(ctx context.Context, in *InstallSkillRequest, opts ...grpc.CallOption) (*InstallSkillResponse, error)
	DownloadSkill(ctx context.Context, in *DownloadSkillRequest, opts ...grpc.CallOption) (*DownloadSkillResponse, error)
	InjectSkill(ctx context.Context, in *InjectSkillRequest, opts ...grpc.CallOption) (*InjectSkillResponse, error)
	InspectSkill(ctx context.Context, in *InspectSkillRequest, opts ...grpc.CallOption) (*InspectSkillResponse, error)
	DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*DeleteSkillResponse, error)
	TrustSkill(ctx context.Context, in *TrustSkillRequest, opts ...grpc.CallOption) (*TrustSkillResponse, error)
	// Auth & Tokens
	GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
	ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteRequest, ExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteClient = grpc.ServerStreamingClient[ExecuteResponse]

func (c *agentServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, AgentService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListHistory(ctx context.Context, in *ListHistoryRequest, opts ...grpc.CallOption) (*ListHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHistoryResponse)
	err := c.cc.Invoke(ctx, AgentService_ListHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationResponse)
	err := c.cc.Invoke(ctx, AgentService_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSupportedProviders(ctx context.Context, in *GetSupportedProvidersRequest, opts ...grpc.CallOption) (*GetSupportedProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportedProvidersResponse)
	err := c.cc.Invoke(ctx, AgentService_GetSupportedProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ConfigureProvider(ctx context.Context, in *ConfigureProviderRequest, opts ...grpc.CallOption) (*ConfigureProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureProviderResponse)
	err := c.cc.Invoke(ctx, AgentService_ConfigureProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, AgentService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DiscoverModels(ctx context.Context, in *DiscoverModelsRequest, opts ...grpc.CallOption) (*DiscoverModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverModelsResponse)
	err := c.cc.Invoke(ctx, AgentService_DiscoverModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RegisterModel(ctx context.Context, in *RegisterModelRequest, opts ...grpc.CallOption) (*RegisterModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterModelResponse)
	err := c.cc.Invoke(ctx, AgentService_RegisterModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SystemEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeEventsRequest, SystemEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SubscribeEventsClient = grpc.ServerStreamingClient[SystemEvent]

func (c *agentServiceClient) GetActiveJobs(ctx context.Context, in *GetActiveJobsRequest, opts ...grpc.CallOption) (*GetActiveJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveJobsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetActiveJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (*ListSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSkillsResponse)
	err := c.cc.Invoke(ctx, AgentService_ListSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetSkillInfo(ctx context.Context, in *GetSkillInfoRequest, opts ...grpc.CallOption) (*GetSkillInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSkillInfoResponse)
	err := c.cc.Invoke(ctx, AgentService_GetSkillInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InstallSkill(ctx context.Context, in *InstallSkillRequest, opts ...grpc.CallOption) (*InstallSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallSkillResponse)
	err := c.cc.Invoke(ctx, AgentService_InstallSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DownloadSkill(ctx context.Context, in *DownloadSkillRequest, opts ...grpc.CallOption) (*DownloadSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadSkillResponse)
	err := c.cc.Invoke(ctx, AgentService_DownloadSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InjectSkill(ctx context.Context, in *InjectSkillRequest, opts ...grpc.CallOption) (*InjectSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InjectSkillResponse)
	err := c.cc.Invoke(ctx, AgentService_InjectSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) InspectSkill(ctx context.Context, in *InspectSkillRequest, opts ...grpc.CallOption) (*InspectSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InspectSkillResponse)
	err := c.cc.Invoke(ctx, AgentService_InspectSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) DeleteSkill(ctx context.Context, in *DeleteSkillRequest, opts ...grpc.CallOption) (*DeleteSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSkillResponse)
	err := c.cc.Invoke(ctx, AgentService_DeleteSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) TrustSkill(ctx context.Context, in *TrustSkillRequest, opts ...grpc.CallOption) (*TrustSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrustSkillResponse)
	err := c.cc.Invoke(ctx, AgentService_TrustSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GenerateToken(ctx context.Context, in *GenerateTokenRequest, opts ...grpc.CallOption) (*GenerateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTokenResponse)
	err := c.cc.Invoke(ctx, AgentService_GenerateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, AgentService_RevokeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ListTokens(ctx context.Context, in *ListTokensRequest, opts ...grpc.CallOption) (*ListTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTokensResponse)
	err := c.cc.Invoke(ctx, AgentService_ListTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService manages the interaction between User Clients and The Brain
type AgentServiceServer interface {
	// Execute sends a natural language query and receives a stream of events
	Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error
	// GetInfo returns the current status and metadata of the Vraxter Engine
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// ListHistory returns the most recent conversations
	ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error)
	// GetConversation returns all messages for a specific conversation
	GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error)
	// GetSupportedProviders returns all registered provider types (google, openai, etc.)
	GetSupportedProviders(context.Context, *GetSupportedProvidersRequest) (*GetSupportedProvidersResponse, error)
	// ConfigureProvider creates or updates a provider configuration
	ConfigureProvider(context.Context, *ConfigureProviderRequest) (*ConfigureProviderResponse, error)
	// ListProviders returns all configured providers
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	// DiscoverModels fetches available models from the provider's API
	DiscoverModels(context.Context, *DiscoverModelsRequest) (*DiscoverModelsResponse, error)
	// RegisterModel saves a discovered model to the local database
	RegisterModel(context.Context, *RegisterModelRequest) (*RegisterModelResponse, error)
	// ListModels returns all registered models, optionally filtered by provider
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// SubscribeEvents opens a persistent, one-way stream from the engine to the client
	// used to push asynchronous background jobs and swarm notifications.
	SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[SystemEvent]) error
	// GetActiveJobs returns all currently tracked background daemons
	GetActiveJobs(context.Context, *GetActiveJobsRequest) (*GetActiveJobsResponse, error)
	// --- Configuration Management ---
	GetConfig(context.Context, *GetConfigRequest) (*ConfigResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*ConfigResponse, error)
	// --- Skills & Hub Management ---
	ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error)
	GetSkillInfo(context.Context, *GetSkillInfoRequest) (*GetSkillInfoResponse, error)
	InstallSkill(context.Context, *InstallSkillRequest) (*InstallSkillResponse, error)
	DownloadSkill(context.Context, *DownloadSkillRequest) (*DownloadSkillResponse, error)
	InjectSkill(context.Context, *InjectSkillRequest) (*InjectSkillResponse, error)
	InspectSkill(context.Context, *InspectSkillRequest) (*InspectSkillResponse, error)
	DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillResponse, error)
	TrustSkill(context.Context, *TrustSkillRequest) (*TrustSkillResponse, error)
	// Auth & Tokens
	GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error)
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	ListTokens(context.Context, *ListTokensRequest) (*ListTokensResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Execute(*ExecuteRequest, grpc.ServerStreamingServer[ExecuteResponse]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedAgentServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedAgentServiceServer) ListHistory(context.Context, *ListHistoryRequest) (*ListHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHistory not implemented")
}
func (UnimplementedAgentServiceServer) GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedAgentServiceServer) GetSupportedProviders(context.Context, *GetSupportedProvidersRequest) (*GetSupportedProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedProviders not implemented")
}
func (UnimplementedAgentServiceServer) ConfigureProvider(context.Context, *ConfigureProviderRequest) (*ConfigureProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureProvider not implemented")
}
func (UnimplementedAgentServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedAgentServiceServer) DiscoverModels(context.Context, *DiscoverModelsRequest) (*DiscoverModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverModels not implemented")
}
func (UnimplementedAgentServiceServer) RegisterModel(context.Context, *RegisterModelRequest) (*RegisterModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterModel not implemented")
}
func (UnimplementedAgentServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedAgentServiceServer) SubscribeEvents(*SubscribeEventsRequest, grpc.ServerStreamingServer[SystemEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedAgentServiceServer) GetActiveJobs(context.Context, *GetActiveJobsRequest) (*GetActiveJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveJobs not implemented")
}
func (UnimplementedAgentServiceServer) GetConfig(context.Context, *GetConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedAgentServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedAgentServiceServer) ListSkills(context.Context, *ListSkillsRequest) (*ListSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSkills not implemented")
}
func (UnimplementedAgentServiceServer) GetSkillInfo(context.Context, *GetSkillInfoRequest) (*GetSkillInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSkillInfo not implemented")
}
func (UnimplementedAgentServiceServer) InstallSkill(context.Context, *InstallSkillRequest) (*InstallSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallSkill not implemented")
}
func (UnimplementedAgentServiceServer) DownloadSkill(context.Context, *DownloadSkillRequest) (*DownloadSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadSkill not implemented")
}
func (UnimplementedAgentServiceServer) InjectSkill(context.Context, *InjectSkillRequest) (*InjectSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectSkill not implemented")
}
func (UnimplementedAgentServiceServer) InspectSkill(context.Context, *InspectSkillRequest) (*InspectSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InspectSkill not implemented")
}
func (UnimplementedAgentServiceServer) DeleteSkill(context.Context, *DeleteSkillRequest) (*DeleteSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSkill not implemented")
}
func (UnimplementedAgentServiceServer) TrustSkill(context.Context, *TrustSkillRequest) (*TrustSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrustSkill not implemented")
}
func (UnimplementedAgentServiceServer) GenerateToken(context.Context, *GenerateTokenRequest) (*GenerateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateToken not implemented")
}
func (UnimplementedAgentServiceServer) RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedAgentServiceServer) ListTokens(context.Context, *ListTokensRequest) (*ListTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTokens not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).Execute(m, &grpc.GenericServerStream[ExecuteRequest, ExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ExecuteServer = grpc.ServerStreamingServer[ExecuteResponse]

func _AgentService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListHistory(ctx, req.(*ListHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSupportedProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportedProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSupportedProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSupportedProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSupportedProviders(ctx, req.(*GetSupportedProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ConfigureProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ConfigureProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ConfigureProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ConfigureProvider(ctx, req.(*ConfigureProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DiscoverModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DiscoverModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DiscoverModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DiscoverModels(ctx, req.(*DiscoverModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RegisterModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterModel(ctx, req.(*RegisterModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeEventsRequest, SystemEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SubscribeEventsServer = grpc.ServerStreamingServer[SystemEvent]

func _AgentService_GetActiveJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetActiveJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetActiveJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetActiveJobs(ctx, req.(*GetActiveJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListSkills(ctx, req.(*ListSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetSkillInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSkillInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetSkillInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetSkillInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetSkillInfo(ctx, req.(*GetSkillInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InstallSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InstallSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InstallSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InstallSkill(ctx, req.(*InstallSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DownloadSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DownloadSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DownloadSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DownloadSkill(ctx, req.(*DownloadSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InjectSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InjectSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InjectSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InjectSkill(ctx, req.(*InjectSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_InspectSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InspectSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).InspectSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_InspectSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).InspectSkill(ctx, req.(*InspectSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_DeleteSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).DeleteSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_DeleteSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).DeleteSkill(ctx, req.(*DeleteSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_TrustSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrustSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).TrustSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_TrustSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).TrustSkill(ctx, req.(*TrustSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GenerateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GenerateToken(ctx, req.(*GenerateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ListTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ListTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ListTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ListTokens(ctx, req.(*ListTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _AgentService_GetInfo_Handler,
		},
		{
			MethodName: "ListHistory",
			Handler:    _AgentService_ListHistory_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _AgentService_GetConversation_Handler,
		},
		{
			MethodName: "GetSupportedProviders",
			Handler:    _AgentService_GetSupportedProviders_Handler,
		},
		{
			MethodName: "ConfigureProvider",
			Handler:    _AgentService_ConfigureProvider_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _AgentService_ListProviders_Handler,
		},
		{
			MethodName: "DiscoverModels",
			Handler:    _AgentService_DiscoverModels_Handler,
		},
		{
			MethodName: "RegisterModel",
			Handler:    _AgentService_RegisterModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _AgentService_ListModels_Handler,
		},
		{
			MethodName: "GetActiveJobs",
			Handler:    _AgentService_GetActiveJobs_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _AgentService_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _AgentService_UpdateConfig_Handler,
		},
		{
			MethodName: "ListSkills",
			Handler:    _AgentService_ListSkills_Handler,
		},
		{
			MethodName: "GetSkillInfo",
			Handler:    _AgentService_GetSkillInfo_Handler,
		},
		{
			MethodName: "InstallSkill",
			Handler:    _AgentService_InstallSkill_Handler,
		},
		{
			MethodName: "DownloadSkill",
			Handler:    _AgentService_DownloadSkill_Handler,
		},
		{
			MethodName: "InjectSkill",
			Handler:    _AgentService_InjectSkill_Handler,
		},
		{
			MethodName: "InspectSkill",
			Handler:    _AgentService_InspectSkill_Handler,
		},
		{
			MethodName: "DeleteSkill",
			Handler:    _AgentService_DeleteSkill_Handler,
		},
		{
			MethodName: "TrustSkill",
			Handler:    _AgentService_TrustSkill_Handler,
		},
		{
			MethodName: "GenerateToken",
			Handler:    _AgentService_GenerateToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _AgentService_RevokeToken_Handler,
		},
		{
			MethodName: "ListTokens",
			Handler:    _AgentService_ListTokens_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _AgentService_Execute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _AgentService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/agent.proto",
}
