package server

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/patagonicrune/vraxter/internal/env"
)

// EnvServiceSkeleton represents what the generated Connect RPC server interface would look like.
// In a true Connect implementation, this would be generated by protoc-gen-connect-go.
type EnvServiceSkeleton struct {
	StateManager *env.StateManager
	Pipeline     *env.ExecutionPipeline
}

func NewEnvServiceSkeleton(sm *env.StateManager, pipeline *env.ExecutionPipeline) *EnvServiceSkeleton {
	return &EnvServiceSkeleton{
		StateManager: sm,
		Pipeline:     pipeline,
	}
}

// GetCurrentState is an HTTP handler simulating a Connect RPC endpoint: `POST /vraxter.env.v1.EnvService/GetCurrentState`
func (s *EnvServiceSkeleton) GetCurrentState(w http.ResponseWriter, r *http.Request) {
	// 1. Thread-safe read
	state := s.StateManager.GetState()

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(state)
}

// SetEnvironmentalState simulates a Connect RPC mutation endpoint.
// It receives a partial state, mutates the active StateManager thread-safely, and triggers the Pipeline.
func (s *EnvServiceSkeleton) SetEnvironmentalState(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req env.EnvironmentalState
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		http.Error(w, "Invalid JSON payload", http.StatusBadRequest)
		return
	}

	// 1. Mutate State safely
	s.StateManager.MutateState(func(state *env.EnvironmentalState) {
		if req.TensionLevel != 0 {
			state.TensionLevel = req.TensionLevel
		}
		if req.ConversationPattern != "" {
			state.ConversationPattern = req.ConversationPattern
		}
		if req.MusicStyle != "" {
			state.MusicStyle = req.MusicStyle
		}
		if len(req.TriggerKeywords) > 0 {
			state.TriggerKeywords = req.TriggerKeywords
		}
		if req.EyeColor != "" {
			state.EyeColor = req.EyeColor
		}
		if req.EyeDynamics != "" {
			state.EyeDynamics = req.EyeDynamics
		}
	})

	// 2. Fetch the newly mutated state
	newState := s.StateManager.GetState()

	// 3. Trigger the debounced execution pipeline
	if err := s.Pipeline.ApplyEnvironmentalChange(newState); err != nil {
		http.Error(w, fmt.Sprintf("Pipeline error: %v", err), http.StatusInternalServerError)
		return
	}

	// 4. Return success
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(`{"status":"success"}`))
}

// RegisterEnvService mounts the Connect RPC handlers onto a standard HTTP multiplexer.
func RegisterEnvService(mux *http.ServeMux, sm *env.StateManager, pipeline *env.ExecutionPipeline) {
	svc := NewEnvServiceSkeleton(sm, pipeline)

	// In a real Connect implementation, this would look like:
	// path, handler := envv1connect.NewEnvServiceHandler(svc)
	// mux.Handle(path, handler)

	// Since we are building the skeleton manually:
	mux.HandleFunc("/vraxter.env.v1.EnvService/GetCurrentState", svc.GetCurrentState)
	mux.HandleFunc("/vraxter.env.v1.EnvService/SetEnvironmentalState", svc.SetEnvironmentalState)
}
